substitutions:
  _APIGEE_HOST: "34.54.45.250.nip.io"
  _APIGEE_ENV: "eval"
  _PROJECT: "oasis-0000"

steps:
  # Step 1: Generate build token
  - name: 'gcr.io/cloud-builders/gcloud'
    id: "Generate token"
    waitFor: ["-"] # start first
    entrypoint: 'bash'
    args:
      - -c
      - |
        export build_token="$(gcloud auth application-default print-access-token)"
        echo "build_token=$build_token" > /workspace/build_vars

  # Step 2: Package bundle with Maven
  - name: 'gcr.io/cloud-builders/mvn'
    id: "Package bundle"
    waitFor: ["Generate token"]
    entrypoint: 'bash'
    args:
      - -c
      - |
        mvn -f pom.xml -ntp process-resources apigee-enterprise:configure \
          -Pdev -Dorg=${_PROJECT} -Denv=${_APIGEE_ENV}

  # Step 3: Manual Approval
  - id: "Approval before deployment"
    name: "gcr.io/cloud-builders/gsutil"
    waitFor: ["Package bundle"]
    args: ["echo", "Waiting for approval..."]
    approval: true

  # Step 4: Deploy bundle with Maven
  - name: 'gcr.io/cloud-builders/mvn'
    id: "Deploy bundle"
    waitFor: ["Approval before deployment"]
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/build_vars
        echo "Token: $build_token"
        mvn -f pom.xml -ntp -X apigee-enterprise:deploy -Pdev -Dorg=${_PROJECT} \
          -Denv=${_APIGEE_ENV} -Dbearer=${build_token} -Doverride=true

  # Step 5: Smoke Test
  - name: 'curlimages/curl'
    id: "Smoke test"
    waitFor: ["Deploy bundle"]
    entrypoint: 'sh'
    args:
      - -c
      - |
        source /workspace/build_vars
        echo "Running smoke test..."
        set -e
        curl -s -o /dev/null -w "%{http_code}" "https://${_APIGEE_HOST}/v1/my-proxy-endpoint" \
          -H "Authorization: Bearer $build_token" \
          | tee /workspace/http_code
        code=$(cat /workspace/http_code)
        if [ "$code" != "200" ]; then
          echo "Smoke test failed with HTTP $code"
          exit 1
        fi
        echo "Smoke test passed"

  # Step 6: Rollback if smoke test fails
  - name: 'gcr.io/cloud-builders/mvn'
    id: "Rollback"
    waitFor: ["Smoke test"]
    entrypoint: 'bash'
    args:
      - -c
      - |
        if [ "$BUILD_STATUS" == "FAILURE" ]; then
          echo "Rolling back to previous revision..."
          source /workspace/build_vars
          mvn -f pom.xml -ntp apigee-enterprise:deploy -Pdev -Dorg=${_PROJECT} \
            -Denv=${_APIGEE_ENV} -Dbearer=${build_token} -Doverride=false -Drollback=true
        else
          echo "No rollback required"
        fi

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
