substitutions:
  _ORG: "oasis-0000"
  _ENV: "eval"      
  _PROXY_NAME: "newproxy"

steps:
  - name: "ghcr.io/apigee/apigeecli:latest"
    id: "deploy-apigee-proxy"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        apigeecli token cache --metadata-token || { echo "Token cache failed"; exit 1; }
        
        apigeecli prefs set --nocheck=true -o $_ORG || { echo "Set org failed"; exit 1; }
        
        for i in {1..3}; do
          apigeecli apis create bundle -f apiproxy --name $_PROXY_NAME && break
          echo "Import attempt $i failed, retrying..."
          sleep 5
        done || { echo "Bundle import failed after retries"; exit 1; }
        
        for i in {1..3}; do
          apigeecli apis deploy --wait --name $_PROXY_NAME --ovr -e $_ENV && break
          echo "Deploy attempt $i failed, retrying..."
          sleep 5
        done || { echo "Deployment failed after retries"; exit 1; }


options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
