substitutions:
  _APIGEE_ENV: "eval"
  _APIGEE_ORG: "oasis-0000"
  _APIGEE_HOST: "34.54.45.250.nip.io"
  _API_NAME: "simple-proxy"

steps:
  # Step 1: Generate OAuth token
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: "Generate token"
    waitFor: ["-"]
    entrypoint: 'bash'
    args:
      - -c
      - |
        export build_token="$(gcloud auth print-access-token)"
        echo "build_token=$build_token" > /workspace/build_vars

  # Step 2: Package the bundle
  - name: 'gcr.io/cloud-builders/mvn'
    id: "Package bundle"
    waitFor: ["Generate token"]
    args:
      - clean
      - package
      - -Pdev
      - -Dorg=${_APIGEE_ORG}
      - -Denv=${_APIGEE_ENV}

  # Step 3: Validate bundle
  - name: 'gcr.io/cloud-builders/mvn'
    id: "Validate bundle"
    waitFor: ["Package bundle"]
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/build_vars
        mvn apigee-x:configure -Pdev \
          -Dorg=${_APIGEE_ORG} \
          -Denv=${_APIGEE_ENV} \
          -Dbearer=$build_token

  # Step 4: Deploy bundle
  - name: 'gcr.io/cloud-builders/mvn'
    id: "Deploy bundle"
    waitFor: ["Validate bundle"]
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/build_vars
        mvn apigee-x:deploy -Pdev \
          -Dorg=${_APIGEE_ORG} \
          -Denv=${_APIGEE_ENV} \
          -Dbearer=$build_token \
          -Doverride=true

  # Step 5: Smoke test
  - name: 'gcr.io/cloud-builders/curl'
    id: "Smoke test"
    waitFor: ["Deploy bundle"]
    allowFailure: true
    entrypoint: 'sh'
    args:
      - -c
      - |
        source /workspace/build_vars
        echo "Running smoke test..."
        http_code=$(curl -s -o /dev/null -w "%{http_code}" "https://${_APIGEE_HOST}/test2")
        echo "http_code=$http_code" >> /workspace/build_vars
        if [ "$http_code" != "200" ]; then
          echo "Smoke test failed with HTTP $http_code"
          exit 1
        fi
        echo "Smoke test passed"

  # Step 6: Rollback if smoke test fails
  - name: 'gcr.io/cloud-builders/mvn'
    id: "Rollback"
    waitFor: ["Smoke test"]
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/build_vars
        if [ "$http_code" != "200" ]; then
          echo "Rolling back to previous revision..."
          mvn apigee-x:deploy -Pdev \
            -Dorg=${_APIGEE_ORG} \
            -Denv=${_APIGEE_ENV} \
            -Dbearer=$build_token \
            -Doverride=false -Drollback=true \
            -Dapigee.api=${_API_NAME}
          exit 1
        else
          echo "No rollback required"
        fi

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
