substitutions:
  # Customize these values (set via trigger or manually override in Cloud Build UI)
  _ORG: "oasis-0000"  # Apigee organization name (often your GCP project ID)
  _ENV: "test"             # Target Apigee environment (e.g., test, prod)
  _PROXY_NAME: "apiproxy"  # Name of the API proxy (must match <Name> in apiproxy/apiproxy.xml)

steps:
  - name: "ghcr.io/apigee/apigeecli:latest"
    id: "deploy-apigee-proxy"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        # Cache access token from Cloud Build metadata (uses service account)
        apigeecli token cache --metadata-token
        
        # Set organization (disables SSL checks if needed for self-signed certs)
        apigeecli prefs set --nocheck=true -o $_ORG
        
        # Import bundle to create new revision (creates proxy if it doesn't exist)
        apigeecli apis create bundle -f apiproxy --name $_PROXY_NAME
        
        # Deploy latest revision to environment (overrides existing deployment, waits for completion)
        apigeecli apis deploy --wait --name $_PROXY_NAME --ovr -e $_ENV

      
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
