substitutions:
  _ORG: “oasis-0000“
  _ENV: "test"      
  _PROXY_NAME: “hello-world”

steps:
  - name: "ghcr.io/apigee/apigeecli:latest"
    id: "deploy-apigee-proxy"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        # Cache access token from Cloud Build metadata
        apigeecli token cache --metadata-token || { echo "Token cache failed"; exit 1; }
        
        # Set organization
        apigeecli prefs set --nocheck=true -o $_ORG || { echo "Set org failed"; exit 1; }
        
        # Import bundle to create new revision (retries up to 3 times for transient errors)
        for i in {1..3}; do
          apigeecli apis create bundle -f apiproxy --name $_PROXY_NAME && break
          echo "Import attempt $i failed, retrying..."
          sleep 5
        done || { echo "Bundle import failed after retries"; exit 1; }
        
        # Deploy latest revision (retries up to 3 times)
        for i in {1..3}; do
          apigeecli apis deploy --wait --name $_PROXY_NAME --ovr -e $_ENV && break
          echo "Deploy attempt $i failed, retrying..."
          sleep 5
        done || { echo "Deployment failed after retries"; exit 1; }
